name: Get OAuth Token
on: [pull_request, push]

jobs:
  get_oauth_token:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get current epoch time
        run: echo "CURRENT_EPOCH=$(date +%s)" >> $GITHUB_ENV

      - name: Check if token has expired
        run: |
          if [[ -z "$GITHUB_ENV{EPOCH_TIME}" || $((CURRENT_EPOCH - EPOCH_TIME)) -gt $((30 * 24 * 60 * 60)) ]]; then
            # Get OAuth token
            curl -X POST \
              -H "Content-Type: application/x-www-form-urlencoded" \
              -d 'grant_type=authorization_code&client_id=YOUR_CLIENT_ID&client_secret=YOUR_CLIENT_SECRET&audience=YOUR_AUDIENCE' \
              https://test.com > $GITHUB_ENV{M2M_ENV}
          else
            echo "Token is still valid."
          fi

      - name: Set environment variable
        run: |
          echo "M2M_TOKEN=$M2M_ENV" >> $GITHUB_ENV