name: Deploy to Cloud Run

on: [push]

jobs:
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    steps:
    
      - name: "Create ENV file"
        run: |
          echo "${{ secrets.BACKEND_ENV }}" >> .env

      - name: Setup GCP Service Account
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@main
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker
        
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
           path: main
      
      - name: Build
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/api:latest .

      - name: Push
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/api:latest

      - name: Deploy
        run: |
          gcloud run deploy helloworld \
          --region asia-east1 \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/api \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }}
